version: '3.9'

services:

  conta-api:
    build:
      context: ./backend/BankMore
      dockerfile: ContaCorrente.API/Dockerfile
    ports:
      - "5001:80"
    # depends_on:
    #   - postgres
    #   - kafka

  transferencia-api:
    build:
      context: ./backend/BankMore
      dockerfile: Transferencia.API/Dockerfile
    ports:
      - "5002:80"
  #   depends_on:
  #     - postgres
  #     - kafka

  # postgres:
  #   image: postgres:15
  #   container_name: bankmore-db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: bankmore
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./database:/docker-entrypoint-initdb.d

  # zookeeper:
  # kafka: